version: "3.3"
services:
  mongo-server:
    image: mongo:latest
    container_name: "mongo-server"
    ports:
    - 27017:27017

  eureka-server:
    build:
      context: Eureka Server
    container_name: eureka-server
    ports:
    - 8761:8761

  movie-info-service:
    build:
      context: Movie Info Service
    container_name: movie-info-service
    ports:
    - 3000:3000
    links:
    - mongo-server
    - eureka-server

  movie-rating-service:
    build:
      context: Movie Rating Service
    container_name: movie-rating-service
    ports:
    - 4000:4000
    links:
    - mongo-server
    - eureka-server

  movie-catalog-service:
    build:
      context: Movie Catalog Service
    container_name: movie-catalog-service
    ports:
    - 2000:2000
    links:
    - eureka-server